education/urls.py
from django.urls import path, include

from education.views import index, courses, lectures, tasks

app_name = 'education'

courses_patterns = [
    path('', courses.list, name='list'),
    path('<int:course_id>/', courses.detail, name='detail'),
    path('new/', courses.CourseCreateView.as_view(), name='create'),
]

lectures_patterns = [
    path('', lectures.list, name='list'),
    path('<int:lecture_id>/', lectures.detail, name='detail'),
    path('new/', lectures.LectureCreateView.as_view(), name='create'),
]

tasks_pattern = [
    path('', tasks.list, name='list'),
    path('<int:task_id>/', tasks.detail, name='detail'),
    path('new/', tasks.TaskCreateView.as_view(), name='create'),
]

urlpatterns = [
    path('', index, name='index'),
    path('courses/', include((courses_patterns, 'courses'))),
    path('lectures/', include((lectures_patterns, 'lectures'))),
    path('tasks/', include((tasks_pattern, 'tasks'))),
]

hackacademy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('education/', include('education.urls')),
    path('admin/', admin.site.urls),
]

education/models.py
from django.db import models
from django.utils import timezone
import requests


class Course(models.Model):
    name = models.CharField(max_length=250, unique=True)
    description = models.TextField()
    start_date = models.DateTimeField(default=timezone.now)
    end_date = models.DateTimeField(null=True)

    def __str__(self):
        return 'Course "{}"'.format(self.name)

    @property
    def duration(self):
        if self.end_date:
            return self.end_date - self.start_date


class Lecture(models.Model):
    lecture_id = models.IntegerField(unique=True, primary_key=True)
    name = models.CharField(max_length=250, unique=True)
    week = models.IntegerField()
    course = models.ForeignKey('Course', on_delete=models.CASCADE)
    url = models.TextField()

    def __str__(self):
        return 'Lecture "{}"'.format(self.name)


class Task(models.Model):
    name = models.CharField(max_length=250, unique=True)
    description = models.TextField()
    due_date = models.DateTimeField()
    course = models.ForeignKey('Course', on_delete=models.CASCADE)
    lecture = models.ForeignKey('Lecture', null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return 'Task "{}"'.format(self.name)


class Solution(models.Model):
    task = models.ForeignKey('Task', on_delete=models.CASCADE)
    date = models.DateTimeField()
    url = models.TextField()

    def __str__(self):
        return 'Solution for "{}"'.format(self.task.name)

    def validate_url(self):
        r = requests.get(self.url)
        if r.headers['server'] == 'GitHub.com':
            return True
        return False

    def clean(self, *args, **kwargs):
        if self.validate_url():
            super(Solution, self).clean(*args, **kwargs)
        else:
            raise ValueError('This is not github repo')

    def save(self, *args, **kwargs):
        self.full_clean()
        super(Solution, self).save(*args, **kwargs)

education/views/courses.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import CreateView
from django.urls import reverse_lazy

from education.models import Course, Lecture, Task


def list(request):
    return render(request, 'courses/list.html', {'courses': Course.objects.all()})


def detail(request, course_id):
    course = get_object_or_404(Course, id=course_id)
    c_name = course.name
    return render(request, 'courses/detail.html', {'course': course,
                                                   'lectures': Lecture.objects.filter(course__name=c_name),
                                                   'tasks': Task.objects.filter(course__name=c_name)})


class CourseCreateView(CreateView):
    model = Course
    fields = ['name', 'description', 'start_date', 'end_date']
    template_name = 'courses/create.html'

    def get_success_url(self, **kwargs):
        return reverse_lazy('education:courses:detail', kwargs={'course_id': self.object.id})

education/views/lectures.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import CreateView
from django.urls import reverse_lazy

from education.models import Lecture, Task


def list(request):
    return render(request, 'lectures/list.html', {'lectures': Lecture.objects.all()})


def detail(request, lecture_id):
    lecture = get_object_or_404(Lecture, lecture_id=lecture_id)
    return render(request, 'lectures/detail.html', {'lecture': lecture,
                                                    'tasks': Task.objects.filter(lecture__name=lecture.name)})


class LectureCreateView(CreateView):
    model = Lecture
    fields = ['lecture_id', 'name', 'week', 'course', 'url']
    template_name = 'lectures/create.html'

    def get_success_url(self, **kwargs):
        return reverse_lazy('education:lectures:detail', kwargs={'lecture_id': self.object.lecture_id})

education/views/tasks.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import CreateView
from django.urls import reverse_lazy

from education.models import Task


def list(request):
    return render(request, 'tasks/list.html', {'tasks': Task.objects.all()})


def detail(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    return render(request, 'tasks/detail.html', {'task': task})


class TaskCreateView(CreateView):
    model = Task
    fields = ['name', 'description', 'due_date', 'course', 'lecture']
    template_name = 'tasks/create.html'

    def get_success_url(self, **kwargs):
        return reverse_lazy('education:tasks:detail', kwargs={'task_id': self.object.id})

education/templates/courses/base.html
<a href="{% url 'education:index' %}">Home</a>
<h1><a href="{% url 'education:courses:list' %}">Courses</a></h1>

{% block content %} {% endblock %}

education/templates/courses/create.html
<h2>Add new course</h2>

<form method="POST">
  {% csrf_token %} {{ form.as_p }}
  <input type="submit" name="Save" />
</form>

education/templates/courses/detail.html
{% extends "courses/base.html" %} 
{% load static %}
{% block content %}
<head>
	<title>{{ course.name }}</title>
	<link rel="stylesheet" href="{% static 'css/courses/detail.css' %}">
</head>
<h1>{{ course.name }}'s Lectures</h1>
<table style="width:100%">
	{% if lectures %}
	<tr>
		<th>Lecture ID</th>
		<th>Lecture name</th>
		<th>Lecture week</th>
		<th>Lecture URL</th>
	</tr>
	{% for lecture in lectures %}
	<tr>
		{% if course.name == lecture.course.name %}
		<th>{{ lecture.lecture_id }}</th>
		<th>{{ lecture.name }} </th>
		<th>{{ lecture.week }}</th>
		<th>{{ lecture.url }}</th>
		{% endif %}
	</tr>
	{% endfor %}	
	{% else %}
	<h2>There are still no lectures associated with this course.</h2>
	{% endif %}
</table>
<h1 style="margin-top:100px">{{ course.name }}'s Tasks</h1>
<table style="width:100%; margin-top:10px">
	{% if tasks %}
	<tr>
		<th>Task name</th>
		<th>Task Description</th>
		<th>Task Due Date</th>
	<tr>
	{% for task in tasks %}
		{% if task.course.name == course.name %}
		<th><a href="{% url 'education:tasks:detail' task.id %}">{{ task.name }}</th>
		<th>{{ task.description }}</th>
		<th>{{ task.due_date }}</th>
		{% endif %}
	</tr>
	{% endfor %}
	{% else %}
	<h2>There are still no tasks associated with this course.</h2>
	{% endif %}
</table>


{% endblock %}

education/templates/courses/list.html
{% extends "courses/base.html" %}
{% load static %}
{% block content %}
<a href="{% url 'education:courses:create' %}">Add new</a>
<head>
	<title>Courses</title>
	<link rel="stylesheet" href="{% static 'css/courses/detail.css' %}">
</head>
{% if courses %}
<table style="width:100%">
	<tr>
		<th>Name</th>
		<th>Description</th>
		<th>Start date</th>
		<th>End date</th>
	</tr>
  {% for course in courses %}
  <tr>
		<th><a href="{% url 'education:courses:detail' course.id%}">{{ course.name }}</a></th>
		<th>{{ course.description }}</th>
		<th>{{ course.start_date }}</th>
		<th>{{ course.end_date }}</th>
  </tr>
  {% endfor %}
</table>
{% else %}
<p><strong>No courses yet.</strong></p>
{% endif %} {% endblock %}

education/templates/index.html
<h1>Welcome to Hackademy!</h1>

<ul>
  <li><a href="{% url 'education:courses:list' %}">Courses</a></li>
  <li><a href="{% url 'education:lectures:list' %}">Lectures</a></li>
  <li><a href="{% url 'education:tasks:list' %}">Tasks</a></li>
</ul>

education/templates/lectures/base.html
<a href="{% url 'education:index' %}">Home</a>
<h1><a href="{% url 'education:lectures:list' %}">Lectures</a></h1>

{% block content %} {% endblock %}

education/templates/lectures/create.html
<h2>Add new lecture</h2>

<form method="POST">
	{% csrf_token %} {{ form.as_p }}
	<input type="submit" name="Save"/>
</form>

education/templates/lectures/detail.html
{% extends "lectures/base.html" %}
{% load static %}
{% block content %}
<head>
	<title>{{ lecture.name }}</title>
	<link rel="stylesheet" href="{% static 'css/courses/detail.css' %}">
</head>
<table style="width:100%">
	<tr>
		<th>Lecture ID</th>
		<th>Name</th>
		<th>Week</th>
		<th>Course</th>
		<th>URL</th>
	</tr>
	<tr>
		<th>{{ lecture.lecture_id }}</th>
		<th>{{ lecture.name }}</th>
		<th>{{ lecture.week }}</th>
		<th>{{ lecture.course }}</th>
		<th>{{ lecture.url }}</th>
	</tr>
</table>
<h2 style="margin-top:100px; text-align: center">Tasks related to {{ lecture.name }}</h2>
<table style="width:100%">
	{% if tasks %}
	{% for task in tasks %}
	<tr>
		<th>Task name</th>
		<th>Task Description</th>
		<th>Task Due Date</th>
	<tr>
		{% if task.lecture.name == lecture.name %}
		<th><a href="{% url 'education:tasks:detail' task.id %}">{{ task.name }}</th>
		<th>{{ task.description }}</th>
		<th>{{ task.due_date }}</th>
		{% endif %}
	</tr>
	{% endfor %}
	{% else %}
	<h2>There are still no tasks associated with this lecture.</h2>
	{% endif %}

</table>

{% endblock %}

education/templates/lectures/list.html
{% extends "lectures/base.html" %}
{% load static %}
{% block content %}
<a href="{% url 'education:lectures:create' %}">Add new lecture</a>
<head>
	<title>Lectures</title>
	<link rel="stylesheet" href="{% static 'css/courses/detail.css' %}">
</head>
{% if lectures %}
<table style="width:100%">
	<tr>
		<th>Lecture ID</th>
		<th>Name</th>
		<th>Week</th>
		<th>Course</th>
		<th>URL</th>
	</tr>
	{% for lecture in lectures %}
	<tr>
		<th>{{ lecture.lecture_id }}</th>
		<th><a href="{% url 'education:lectures:detail' lecture.lecture_id%}">{{ lecture.name }}</a></th>
		<th>{{ lecture.week }}</th>
		<th><a href="{% url 'education:courses:detail' lecture.course.id%}">{{ lecture.course.name }}</a></th>
		<th>{{ lecture.url }}</th>
	</tr>
	{% endfor %}
</table>
{% else %}
<p><strong>No lectures yet.</strong></p>
{% endif %} {% endblock %}

education/templates/tasks/base.html
<a href="{% url 'education:index' %}">Home</a>
<h1><a href="{% url 'education:tasks:list' %}">Tasks</a></h1>

{% block content %} {% endblock %}

education/templates/tasks/create.html
<h2>Add new Task</h2>

<form method="POST">
	{% csrf_token %} {{ form.as_p }}
	<input type="submit" name="Save" />
</form>

education/templates/tasks/detail.html
{% extends "tasks/base.html" %}
{% load static %}
{% block content %}
<head>
	<title>{{ task.name }}</title>
	<link rel="stylesheet" href="{% static 'css/courses/detail.css' %}">
</head>
<table style="width:100%">
	<tr>
		<th>Name</th>
		<th>Description</th>
		<th>Due Date</th>
		<th>Course</th>
		<th>Lecture</th>
	</tr>
	<tr>
		<th>{{ task.name }}</th>
		<th>{{ task.description }}</th>
		<th>{{ task.due_date }}</th>
		<th>{{ task.course.name }}</th>
		<th>{{ task.lecture.name }}</th>
	</tr>
</table>

{% endblock %}

education/templates/tasks/list.html
{% extends "tasks/base.html" %}
{% load static %}
{% block content %}
<a href="{% url 'education:tasks:create' %}">Add new task</a>
<head>
	<title>Tasks</title>
	<link rel="stylesheet" href="{% static 'css/courses/detail.css' %}">
</head>
{% if tasks %}
<table style="width:100%">
	<tr>
		<th>Name</th>
		<th>Description</th>
		<th>Due Date</th>
		<th>Course</th>
		<th>Lecture</th>
	</tr>
	{% for task in tasks %}
	<tr>
		<th>{{ task.name }}</th>
		<th>{{ task.description }}</th>
		<th>{{ task.due_date }}</th>
		<th><a href="{% url 'education:courses:detail' task.course.id %}">{{ task.course.name }}</a></th>
		{% if task.lecture.name %}
		<th><a href="{% url 'education:lectures:detail' task.lecture.lecture_id %}">{{ task.lecture.name }}</a></th>
		{% else %}
		<th>This task is not associated with lecture</th>
		{% endif %}
	</tr>
	{% endfor %}
</table>
{% else %}
<p><strong>No tasks yet.</strong></p>
{% endif %} {% endblock %}